version: '3.7'

services:
  application_server:
    image: kernelpanic_blog:latest
    build:
      context: .
      args:
        WORK_DIRECTORY: ${WORK_DIRECTORY}
    container_name: blog_application_server
    ports:
      - '80:3000'
    volumes:
      - "../:${WORK_DIRECTORY}"
    working_dir: ${WORK_DIRECTORY}
    tty: true
  database:
    image: postgres:12.11
    container_name: ${DATABASE_HOST}
    ports:
      - '5432:5432'
    volumes:
      - '../.postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}